# piratelex.py - regex transformations for pirate speak
import re

import lex


money_lst = ["gold",
            "treasure",
        ]

lex_values = [
    (r"\b[Mm]y\b", "me"),
    (r"\b([Bb]oss|[Mm]anager)\b", "admiral"),
    (r"\b[Cc]aptain\b", "cap\'n"),
    (r"\b([Ff]riends|[Bb]uddies)\b", "crew"),
    (r"\b([Dd]elete|[Ee]rase|[Tt]hrowaway)\b", "scuttle"),
    (r"\b([Dd]eleted|[Ee]rased|[Tt]hr(ew|own) away)\b", "scuttled"),
    (r"\b[Mm]yself\b", "meself"),
    (r"\b[Yy]our\b", "yer"),
    (r"\b[Yy]ou\b", "ye"),
    (r"\b[Ff]riend\b", "matey"),
    (r"\b[Ff]riends\b", "maties"),
    (r"\b[Cc]o(-)?worker\b", "shipmate"),
    (r"\b[Cc]o(-)?workers\b", "shipmates"),
    (r"\b[Pp]erson\b", "landlubber"),
    (r"\b[Pp]eople\b", "landlubbers"),
    (r"\b[Gg]uys\b", "scurvey dogs"),
    (r"\b([Bb]efore|[Ee]arlier)\b", "afore"),
    (r"\b[Oo]ld\b", "auld"),
    (r"\b[Tt]he\b", "th\'"),
    (r"\b[Oo]f\b", "o\'"),
    (r"\b[Dd]o(n'| no)t\b", "dern\'t"),
    (r"\b[Nn]ever\b", "ne'er"),
    (r"\b[Ee]ver\b", "e\'er"),
    (r"\b[Oo]ver\b", "o\'er"),
    (r"\b[Yy](es|eah|up)\b", "aye"),
    (r"\b[Nn](o|ah|ope)\b", "nay"),
    (r"\b[Dd]on't\ know\b", "dinna"),
    (r"\[Hh]a(d|ve)n't\b", "ha\'nae"),
    (r"\b[Dd]idn't\b", "di\'nae"),
    (r"[Ww]asn't\b", "weren\'t"),
    (r"\b[Ff]or\b", "fer"),
    (r"\b[Bb]etween\b", "betwixt"),
    (r"\b[Aa]round\b", "aroun\'"),
    (r"\b[Tt]o\b", "t\'"),
    (r"\bIt's\b", "\'Tis"),
    (r"\bit's\b", "\'tis"),
    (r"\b([Ww]oman|[Ll]ady)\b", "wench"),
    (r"\b[Ww]ife\b", "lady"),
    (r"\b[Gg]irl\b", "lass"),
    (r"\b[Gg]irls\b", "lassies"),
    (r"\b([Gg]uy|[Mm]an|[Ff]ellow|[Dd]ude)\b", "lubber"),
    (r"\b[Bb]oy\b", "lad"),
    (r"\b[Bb]oys\b", "laddies"),
    (r"\b[Aa]m\b", "be"),
    (r"\b[Aa]re\b", "be"),
    (r"\b[Cc]hildren\b", "little sandcrabs"),
    (r"\b[Kk]ids\b", "minnows"),
    (r"\b[Hh]im\b", "that scurvey dog"),
    (r"\b[Hh]er\b", "that comely wench"),
    (r"\b[Hh]im\.\b", "that drunken sailor."),
    (r"\b[Hh]er\.\b", "that comely lass."),
    (r"\b[Hh]e\b", "that ornery cuss"),
    (r"\b[Ss]he\b", "that winsome lass"),
    (r"\b[Hh]e's\b", "he be"),
    (r"\b[Ss]he's\b", "she be"),
    (r"\b[Tt]hey're\b", "they be"),
    (r"\bwas\b", "were bein\'"),
    (r"\b[Hh](ey|i|ello)\b", "avast"),
    (r"\b[Oo]cean\b", "high seas"),
    (r"\b[Ff]ood\b", "chow"),
    (r"\b[Rr]oad\b", "sea"),
    (r"\b[Ff]reeway\b", "high seas"),
    (r"\b[Rr]oads\b", "seas"),
    (r"\b[Ss]treet\b", "river"),
    (r"\b[Ss]treets\b", "rivers"),
    (r"\b[Hh]ighway\b", "ocean"),
    (r"\b[Hh]ighways\b", "oceans"),
    (r"\b[Cc]ar\b", "boat"),
    (r"\b[Cc]ars\b", "boats"),
    (r"\b[Tt]ruck\b", "schooner"),
    (r"\b[Tt]rucks\b", "schooners"),
    (r"\bSUV\b", "ship"),
    (r"\b([Aa]irplane|[Jj]et)\b", "flying machine"),
    (r"\b[Mm]achine\b", "contraption"),
    (r"\b[Dd]riving|[Tt]ravel(l)ing\b", "sailing"),
    (r"\b([Ss]hit!|[Dd]amn!)\b", "Arrrr!"),
    (r"\b([Aa]ss|[Bb]utt)\b", "dungbie"),
    (r"\b([Cc]heat|[Ff]raud)\b", "hornswaggle"),
    (r"\b([Cc]heated|[Dd]efrauded)\b", "hornswaggled"),
    (r"\b[Pp]irate\b", "buccaneer"),
    (r"\b([Bb]eer|[Ww]ine|[Bb]ooze)\b", "grog"),
    (r"\b[Bb]asement\b", "bilge"),
    (r"\b[Pp]unish\b", "keel-haul"),
    (r"\b[Pp]unished\b", "keel-hauled"),
    (r"\b[Dd]ollar\b", "doubloon"),
    (r"\b[Dd]ollars\b", "doubloons"),
    (r"\b[Mm]oney\b", lambda x: lex.pick(money_lst, x.group())),
    (r"\b([Dd]rive|[Tt]ravel)\b", "sail"),
    (r"\b([Dd]rove|[Tt]ravel(l)ed)\b", "sailed"),
]

lex_patterns = []

for item in lex_values:
    lex.add(lex_patterns, item[0], item[1])

